### ISSUE TITLE
Update the excel file

### ISSUE THREAD

**Issue by agentilb** [cern-sis/cern-authors-guide#10]
Please could you update the excel file with this new version:
- Some lines have been added (publisher AAAS + IOP)
- Some existing lines have been modified (Publisher IOP). 
Let me know if you have any question. 
[journal_list_author_tool_11-04-2023.xlsx](https://github.com/cern-sis/cern-authors-guide/files/11202115/journal_list_author_tool_11-04-2023.xlsx)

**Comment by drjova** [comment]
Deployed https://github.com/cern-sis/cern-authors-guide/releases/tag/v0.0.8
