### ISSUE TITLE
Replace excel file 

### ISSUE THREAD

**Issue by agentilb** [cern-sis/cern-authors-guide#5]
Hello,
Would it be possible to remplace the current file with [this one](https://github.com/cern-sis/cern-authors-guide/files/9535456/journal_list_author_tool-20220909.xlsx)?
https://github.com/cern-sis/cern-authors-guide/blob/master/src/data/journal_list_author_tool.xlsx
And let me know when this is done, 

Thanks in advance,

Anne

**Comment by drjova** [comment]
@agentilb updated!
